### ISSUE TITLE
Refund please?

### ISSUE THREAD

**Issue by abduramann** [baromjon/ramupthemoon#4]
Hi,

I sent 11.3527 EOS ([Tx](https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262)) mistakenly to the contract. Could you refund it? 

Thank you so much.

**Comment by caolei888888** [comment]
?

**Comment by caolei888888** [comment]
?




On 12/01/2019 20:40, abduramann wrote:

Hi,

I sent 11.3527 EOS mistakenly to the contract. Could you refund it?

Thank you so much.

**Comment by caolei888888** [comment]
?




On 12/01/2019 20:54, a15528276213 wrote:
?




On 12/01/2019 20:40, abduramann wrote:

Hi,

I sent 11.3527 EOS mistakenly to the contract. Could you refund it?

Thank you so much.

**Comment by caolei888888** [comment]
看不懂

**Comment by abduramann** [comment]
你好

我错误地将11.3527 EOS（https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262）发送给了合同。 您可以退款吗？

非常感谢。

**Comment by abduramann** [comment]
你好

我向合同錯誤地發送了11.3527 EOS（https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262）。 您可以退款嗎？

非常感謝。

**Comment by caolei888888** [comment]
你找错人了吧？




On 12/01/2019 21:43, abduramann wrote:

你好

我向合同錯誤地發送了11.3527 EOS（https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262）。 您可以退款嗎？

非常感謝。

**Comment by abduramann** [comment]
我嘗試聯繫baromjon

**Comment by caolei888888** [comment]
我没收到你的eos




On 12/01/2019 21:57, abduramann wrote:

我嘗試聯繫baromjon

**Comment by caolei888888** [comment]
你的eos发到什么地方了




On 12/01/2019 21:57, caolei888888 wrote:
我没收到你的eos




On 12/01/2019 21:57, abduramann wrote:

我嘗試聯繫baromjon

**Comment by abduramann** [comment]
ramupthemoon帳戶

**Comment by caolei888888** [comment]
不是我的账户




On 12/01/2019 22:00, abduramann wrote:

ramupthemoon帳戶

**Comment by abduramann** [comment]
與您的帳戶無關。 我沒和你聯繫 我開了一個問題。

這是Tx ID：
https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262

**Comment by caolei888888** [comment]
哦




On 12/01/2019 22:02, abduramann wrote:

與您的帳戶無關。 我沒和你聯繫 我開了一個問題。

這是Tx ID：
https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262

**Comment by abduramann** [comment]
Thank you so much @baromjon
