### ISSUE TITLE
我只抵押了1Kb内存，但是我转100RUTM去赎回，多余的部份没有退回给我?

### ISSUE THREAD

**Issue by zhang-qian-gz** [baromjon/ramupthemoon#7]
我只抵押了1Kb内存，但是我转100RUTM去赎回，多余的部份没有退回给我?

**Comment by baromjon** [comment]
For your questions, please go to the link below to submit, thanks.

[https://github.com/baromjon/ramupthemoon/issues/10#issue-533809502](url)
