### ISSUE TITLE
baromjon, could you refund my EOS which I sent mistakenly?

### ISSUE THREAD

**Issue by abduramann** [baromjon/ramupthemoon#9]
Hi,

I sent 11.3527 EOS ([Tx](https://bloks.io/transaction/b9dfead752afd0a873e6fa162ac7688c211d9279ec69d1d2d234b60da7494262)) mistakenly to the contract. Could you refund it? (to the address from which I sent)

Thank you so much.

**Comment by baromjon** [comment]
11.3527 EOS has been returned, please check the transaction ID 3 fe2561232fff7a6c12cb6531cefb68b7ee9801839b5f148a5123d86ae48ba81
